fig=figure;
% semilogx(tspan,Hst(:,1),':','Color','blue','LineWidth',1);
% hold on;
% semilogx(tspan,HIt(:,1),':','Color','#7f7f7f','LineWidth',1);
% semilogx(tspan,Het(:,1),':','Color','red','LineWidth',1);
% semilogx(tspan,Hst(:,2),'--','Color','blue','LineWidth',1);
% semilogx(tspan,HIt(:,2),'--','Color','#7f7f7f','LineWidth',1);
% semilogx(tspan,Het(:,2),'--','Color','red','LineWidth',1);
% semilogx(tspan,Hst(:,3),'-.','Color','blue','LineWidth',1);
% semilogx(tspan,HIt(:,3),'-.','Color','#7f7f7f','LineWidth',1);
% semilogx(tspan,Het(:,3),'-.','Color','red','LineWidth',1);
% semilogx(tspan,Hst(:,4),'+','Color','blue','LineWidth',0.5);
% semilogx(tspan,HIt(:,4),'+','Color','#7f7f7f','LineWidth',0.5);
% semilogx(tspan,Het(:,4),'+','Color','red','LineWidth',0.5);
semilogx(tspan,Hst(:,5),'Color','blue','LineWidth',1);
hold on;
semilogx(tspan,HIt(:,5),'Color','#7f7f7f','LineWidth',1);
semilogx(tspan,Het(:,5),'Color','red','LineWidth',1);
ylim([-2,22]);
xlabel('t');
ylabel('H');
hold off;
set(fig, 'Position', [100, 100, 800, 350]);

fig = figure;
% semilogx(tspan,S(:,1)/log(min(Ns,Ne)),':','Color','blue','LineWidth',1);
% hold on;
% semilogx(tspan,S(:,2)/log(min(Ns,Ne)),'--','Color','blue','LineWidth',1);
% semilogx(tspan,S(:,3)/log(min(Ns,Ne)),'-.','Color','blue','LineWidth',1);
% semilogx(tspan,S(:,4)/log(min(Ns,Ne)),'+','Color','blue','LineWidth',0.5);
semilogx(tspan,S(:,5)/log(min(Ns,Ne)),'Color','blue','LineWidth',1);
xlabel('t');
ylabel('S/S_{max}');
set(fig, 'Position', [100, 100, 800, 225]);


% fig=figure;
% semilogx(tspan,Hst(:,1),'Color','#0000FF','LineWidth',1);
% hold on;
% semilogx(tspan,HIt(:,1),'Color','#7f7f7f','LineWidth',0.5);
% semilogx(tspan,Het(:,1),'Color','#FF0000','LineWidth',1);
% semilogx(tspan,Hst(:,2),'Color','#0000cf','LineWidth',1);
% semilogx(tspan,HIt(:,2),'Color','#000000','LineWidth',0.5);
% semilogx(tspan,Het(:,2),'Color','#cf0000','LineWidth',1);
% semilogx(tspan,Hst(:,3),'Color','#4f4fff','LineWidth',1);
% semilogx(tspan,HIt(:,3),'Color','#4f4f4f','LineWidth',0.5);
% semilogx(tspan,Het(:,3),'Color','#ff4f4f','LineWidth',1);
% semilogx(tspan,Hst_r(:,1),':','Color','#0000FF','LineWidth',1);
% semilogx(tspan,HIt_r(:,1),':','Color','#7f7f7f','LineWidth',0.5);
% semilogx(tspan,Het_r(:,1),':','Color','#FF0000','LineWidth',1);
% semilogx(tspan,Hst_r(:,2),':','Color','#0000cf','LineWidth',1);
% semilogx(tspan,HIt_r(:,2),':','Color','#000000','LineWidth',0.5);
% semilogx(tspan,Het_r(:,2),':','Color','#cf0000','LineWidth',1);
% semilogx(tspan,Hst_r(:,3),':','Color','#4f4fff','LineWidth',1);
% semilogx(tspan,HIt_r(:,3),':','Color','#4f4f4f','LineWidth',0.5);
% semilogx(tspan,Het_r(:,3),':','Color','#ff4f4f','LineWidth',1);
% ylim([-2,23]);
% xlabel('t');
% ylabel('H');
% hold off;
% set(fig, 'Position', [100, 100, 800, 400]);
% 
% fig = figure;
% semilogx(tspan,S(:,1)/log(min(Ns,Ne)),'Color','#0000ff','LineWidth',1);
% hold on;
% semilogx(tspan,S(:,2)/log(min(Ns,Ne)),'Color','#0000cf','LineWidth',1);
% semilogx(tspan,S(:,3)/log(min(Ns,Ne)),'Color','#4f4fff','LineWidth',1);
% semilogx(tspan,S_r(:,1)/log(min(Ns,Ne)),':','Color','#0000ff','LineWidth',1);
% semilogx(tspan,S_r(:,2)/log(min(Ns,Ne)),':','Color','#0000cf','LineWidth',1);
% semilogx(tspan,S_r(:,3)/log(min(Ns,Ne)),':','Color','#4f4fff','LineWidth',1);
% xlabel('t');
% ylabel('S/S_{max}');
% set(fig, 'Position', [100, 100, 800, 275]);